from __future__ import annotations

# This module is a data owner for long generated-contract prose. Keep the text
# stable for contract generation; line wrapping would make the table harder to
# audit than the intentional long strings.
# ruff: noqa: E501

from envctl_engine.runtime_feature_definition_schema import FeatureDefinition


EXTRA_FEATURES: tuple[FeatureDefinition, ...] = (
    FeatureDefinition(
        area="launcher",
        feature="Top-level envctl launcher resolves repo root, honors --repo, and forwards commands into the runtime",
        user_visible=True,
        shell_source_of_truth=(),
        python_source_of_truth=(
            "python/envctl_engine/runtime/launcher_cli.py",
            "python/envctl_engine/runtime/launcher_support.py",
        ),
        evidence_tests=(
            "tests/python/runtime/test_command_exit_codes.py",
            "tests/python/runtime/test_cli_packaging.py",
        ),
        parity_status="verified_python",
        notes="The top-level launcher now delegates repo resolution, doctor, and forwarding behavior through the Python launcher module.",
        current_behavior="The shell launcher owns repo-root resolution and command forwarding before the Python runtime starts.",
        missing_python_behavior="Decide whether repo resolution should remain a launcher concern or move into Python, and then prove the chosen contract independently of shell behavior.",
        python_owner_module="python/envctl_engine/runtime/cli.py",
        proposed_tests=("tests/python/runtime/test_command_exit_codes.py",),
        severity="high",
        rollout_risk="Launcher regressions can make envctl unusable before Python runtime logic even begins.",
        wave="Wave A",
    ),
    FeatureDefinition(
        area="launcher",
        feature="envctl install writes a shell-file hook block that exposes envctl on PATH",
        user_visible=True,
        shell_source_of_truth=(),
        python_source_of_truth=(
            "python/envctl_engine/runtime/launcher_cli.py",
            "python/envctl_engine/runtime/launcher_support.py",
            "python/envctl_engine/runtime/cli.py",
        ),
        evidence_tests=(
            "tests/python/runtime/test_command_exit_codes.py",
            "tests/python/runtime/test_cli_packaging.py",
        ),
        parity_status="verified_python",
        notes="Install is now implemented and tested in Python for both the installed CLI and the top-level launcher wrapper.",
        current_behavior="Install is implemented entirely in shell wrapper/installer code and remains outside Python runtime ownership.",
        missing_python_behavior="Define the long-term ownership model for install behavior and prove it with stable tests that do not assume shell runtime semantics.",
        python_owner_module="python/envctl_engine/runtime/cli.py",
        proposed_tests=("tests/python/runtime/test_command_exit_codes.py",),
        severity="high",
        rollout_risk="Install regressions directly affect package adoption and first-run UX.",
        wave="Wave A",
    ),
    FeatureDefinition(
        area="launcher",
        feature="envctl uninstall removes the shell-file hook block cleanly and idempotently",
        user_visible=True,
        shell_source_of_truth=(),
        python_source_of_truth=(
            "python/envctl_engine/runtime/launcher_cli.py",
            "python/envctl_engine/runtime/launcher_support.py",
            "python/envctl_engine/runtime/cli.py",
        ),
        evidence_tests=(
            "tests/python/runtime/test_command_exit_codes.py",
            "tests/python/runtime/test_cli_packaging.py",
        ),
        parity_status="verified_python",
        notes="Uninstall is now implemented and tested in Python for both the installed CLI and the top-level launcher wrapper.",
        current_behavior="Uninstall is implemented by the shell installer path and has no Python-owned equivalent.",
        missing_python_behavior="Capture uninstall semantics as an explicit contract and prove idempotent removal behavior independent of shell runtime assumptions.",
        python_owner_module="python/envctl_engine/runtime/cli.py",
        proposed_tests=("tests/python/runtime/test_command_exit_codes.py",),
        severity="medium",
        rollout_risk="Uninstall drift is less severe than install drift but still affects trust in the package workflow.",
        wave="Wave A",
    ),
    FeatureDefinition(
        area="cli",
        feature="Python command parser remains aligned with the supported public command and flag surface",
        user_visible=True,
        shell_source_of_truth=(),
        python_source_of_truth=("python/envctl_engine/runtime/command_router.py",),
        evidence_tests=(
            "tests/python/runtime/test_cli_router_parity.py",
            "tests/python/runtime/test_engine_runtime_command_parity.py",
        ),
        parity_status="verified_python",
        notes="Parser compatibility is now enforced against the Python-owned public command and documentation surface.",
    ),
    FeatureDefinition(
        area="planning",
        feature="Interactive planning selection and count synchronization preserve existing runs while adding or removing trees",
        user_visible=True,
        shell_source_of_truth=(),
        python_source_of_truth=(
            "python/envctl_engine/planning/worktree_domain.py",
            "python/envctl_engine/startup/startup_orchestrator.py",
        ),
        evidence_tests=(
            "tests/python/planning/test_planning_textual_selector.py",
            "tests/python/runtime/test_engine_runtime_real_startup.py",
        ),
        parity_status="verified_python",
        notes="Planning add/remove/zero-scale synchronization, existing-run reuse, and archive behavior are covered by planning and real-startup tests.",
        current_behavior="Python plan selection handles scale-up/down and existing-run reuse, but these flows are still among the most behaviorally rich parts of the old shell runtime.",
        missing_python_behavior="Exhaustively prove plan selection, run reuse, and interactive handoff semantics across add/remove/zero-scale transitions so shell is no longer needed as a behavior oracle.",
        python_owner_module="python/envctl_engine/planning/worktree_domain.py",
        proposed_tests=(
            "tests/python/planning/test_planning_worktree_setup.py",
            "tests/python/runtime/test_engine_runtime_real_startup.py",
        ),
        severity="medium",
        rollout_risk="Plan-selection regressions create high user confusion because they can restart, remove, or preserve the wrong trees.",
        wave="Wave B",
    ),
    FeatureDefinition(
        area="planning",
        feature="Worktree setup flags reuse, recreate, and include-existing-worktrees behave consistently across planning workflows",
        user_visible=True,
        shell_source_of_truth=(),
        python_source_of_truth=(
            "python/envctl_engine/planning/worktree_domain.py",
            "python/envctl_engine/runtime/command_router.py",
        ),
        evidence_tests=(
            "tests/python/planning/test_planning_worktree_setup.py",
            "tests/python/runtime/test_engine_runtime_real_startup.py",
        ),
        parity_status="verified_python",
        notes="Setup-worktree reuse, recreate, and include-existing flag behavior is covered by planning/runtime tests.",
        current_behavior="Setup-worktree and include-existing-worktrees flags are present, but parity evidence is still mostly external and shell-era.",
        missing_python_behavior="Inventory and prove reuse/recreate/include flag semantics in Python planning/worktree tests so setup flows are no longer shell-defined by implication.",
        python_owner_module="python/envctl_engine/planning/worktree_domain.py",
        proposed_tests=("tests/python/planning/test_planning_worktree_setup.py",),
        severity="medium",
        rollout_risk="Worktree setup flags can be destructive, so parity gaps here risk accidental reuse or recreation of the wrong tree.",
        wave="Wave B",
    ),
    FeatureDefinition(
        area="requirements",
        feature="Dependency startup and cleanup remain symmetric for postgres, redis, supabase, and n8n across startup, stop, blast, and planning scale-down",
        user_visible=True,
        shell_source_of_truth=(),
        python_source_of_truth=(
            "python/envctl_engine/requirements/orchestrator.py",
            "python/envctl_engine/runtime/engine_runtime_lifecycle_support.py",
        ),
        evidence_tests=(
            "tests/python/runtime/test_engine_runtime_lifecycle_support.py",
            "tests/python/requirements/test_requirements_orchestrator.py",
        ),
        parity_status="verified_python",
        notes="Dependency startup and cleanup symmetry is covered by runtime lifecycle, requirements orchestrator, and adapter parity tests.",
        current_behavior="Python requirement startup works, but the shell stack still represents the older complete behavior for cleanup symmetry across dependency families.",
        missing_python_behavior="Prove symmetric startup/cleanup behavior for every dependency family across startup, restart, blast-all, blast-worktree, and planning scale-down.",
        python_owner_module="python/envctl_engine/requirements/orchestrator.py",
        proposed_tests=(
            "tests/python/runtime/test_engine_runtime_lifecycle_support.py",
            "tests/python/requirements/test_requirements_orchestrator.py",
        ),
        severity="high",
        rollout_risk="Lifecycle asymmetry leaves dependency resources behind and is one of the fastest ways to make future runs unreliable.",
        wave="Wave C",
    ),
    FeatureDefinition(
        area="requirements",
        feature="Supabase lifecycle, project naming, and container cleanup remain stable for long project names and repeated plan cycles",
        user_visible=True,
        shell_source_of_truth=(),
        python_source_of_truth=(
            "python/envctl_engine/requirements/supabase.py",
            "python/envctl_engine/requirements/supabase_lifecycle/orchestrator.py",
            "python/envctl_engine/requirements/common.py",
            "python/envctl_engine/requirements/common_contracts.py",
            "python/envctl_engine/requirements/docker_runtime.py",
            "python/envctl_engine/requirements/docker_image_support.py",
            "python/envctl_engine/requirements/container_state_support.py",
        ),
        evidence_tests=(
            "tests/python/requirements/test_supabase_requirements_reliability.py",
            "tests/python/requirements/test_requirements_common.py",
        ),
        parity_status="verified_python",
        notes="Supabase naming, cleanup, and repeated lifecycle behavior are covered by dedicated reliability and lifecycle tests.",
        current_behavior="Python Supabase support is real and tested, but legacy shell behavior is still the broader historical reference for repeated cleanup and naming edge cases.",
        missing_python_behavior="Fully prove long-name naming, stale-container cleanup, and repeated lifecycle behavior without needing shell as the fallback oracle.",
        python_owner_module="python/envctl_engine/requirements/supabase_lifecycle/orchestrator.py",
        proposed_tests=(
            "tests/python/requirements/test_supabase_requirements_reliability.py",
            "tests/python/runtime/test_engine_runtime_lifecycle_support.py",
        ),
        severity="high",
        rollout_risk="Supabase cleanup and naming bugs directly block startup and are expensive for users to diagnose manually.",
        wave="Wave C",
    ),
    FeatureDefinition(
        area="requirements",
        feature="Seed or copy-db-storage behavior for per-tree requirements remains consistent with existing workflows",
        user_visible=True,
        shell_source_of_truth=(),
        python_source_of_truth=(
            "python/envctl_engine/requirements/supabase.py",
            "python/envctl_engine/requirements/supabase_lifecycle/orchestrator.py",
            "python/envctl_engine/runtime/command_router.py",
        ),
        evidence_tests=(
            "tests/python/runtime/test_engine_runtime_real_startup.py",
            "tests/python/requirements/test_requirements_orchestrator.py",
        ),
        parity_status="verified_python",
        notes="Seed and copy-db-storage behavior is covered by runtime startup and requirements tests.",
        current_behavior="Seed/copy-db flags still carry shell-era expectations and are not yet expressed as a full Python-owned contract.",
        missing_python_behavior="Define the exact retained seeding behavior and cover it with Python and end-to-end tests so the feature is no longer implicitly shell-defined.",
        python_owner_module="python/envctl_engine/requirements/supabase_lifecycle/orchestrator.py",
        proposed_tests=("tests/python/requirements/test_requirements_orchestrator.py",),
        severity="high",
        rollout_risk="Incorrect seeding semantics can corrupt developer expectations and destroy trust in tree isolation.",
        wave="Wave C",
    ),
    FeatureDefinition(
        area="artifacts",
        feature="Run state, runtime map, ports manifest, and error report remain the authoritative per-run artifact set",
        user_visible=True,
        shell_source_of_truth=(),
        python_source_of_truth=(
            "python/envctl_engine/state/repository.py",
            "python/envctl_engine/runtime/engine_runtime_artifacts.py",
        ),
        evidence_tests=(
            "tests/python/state/test_state_repository_contract.py",
            "tests/python/runtime/test_engine_runtime_artifacts.py",
        ),
        parity_status="verified_python",
        notes="Core runtime artifacts are already Python-owned and well covered.",
    ),
    FeatureDefinition(
        area="artifacts",
        feature="Test results and review artifacts live under the scoped runtime /tmp tree and retain valid dashboard links",
        user_visible=True,
        shell_source_of_truth=(),
        python_source_of_truth=(
            "python/envctl_engine/state/repository.py",
            "python/envctl_engine/actions/project_action_domain.py",
        ),
        evidence_tests=(
            "tests/python/state/test_state_repository_contract.py",
            "tests/python/actions/test_actions_cli.py",
            "tests/python/actions/test_actions_parity.py",
        ),
        parity_status="verified_python",
        notes="Artifact relocation into runtime scope is Python-owned and covered by focused tests.",
    ),
    FeatureDefinition(
        area="artifacts",
        feature="Artifact retention and cleanup remain correct across stop, blast, resume, and plan scale-down flows",
        user_visible=True,
        shell_source_of_truth=(),
        python_source_of_truth=(
            "python/envctl_engine/state/repository.py",
            "python/envctl_engine/runtime/lifecycle_cleanup_orchestrator.py",
        ),
        evidence_tests=(
            "tests/python/state/test_state_repository_contract.py",
            "tests/python/runtime/test_lifecycle_parity.py",
        ),
        parity_status="verified_python",
        notes="Artifact retention and cleanup semantics are covered by state repository and lifecycle parity tests.",
        current_behavior="Python artifacts are scoped correctly, but retention and cleanup semantics across all lifecycle transitions are not yet expressed as a full parity contract.",
        missing_python_behavior="Codify artifact retention expectations for stop, blast, resume, and plan scale-down, then cover them with focused repository and lifecycle tests.",
        python_owner_module="python/envctl_engine/state/repository.py",
        proposed_tests=(
            "tests/python/state/test_state_repository_contract.py",
            "tests/python/runtime/test_lifecycle_parity.py",
        ),
        severity="medium",
        rollout_risk="Artifact cleanup regressions can leave stale state that confuses later runs and operator debugging.",
        wave="Wave E",
    ),
    FeatureDefinition(
        area="diagnostics",
        feature="Release or shipability checks reflect the retained product contract instead of historical shell migration governance",
        user_visible=False,
        shell_source_of_truth=(),
        python_source_of_truth=(
            "python/envctl_engine/runtime/release_gate.py",
            "python/envctl_engine/debug/doctor_orchestrator.py",
        ),
        evidence_tests=(
            "tests/python/runtime/test_release_shipability_gate.py",
            "tests/python/runtime/test_cutover_gate_truth.py",
        ),
        parity_status="verified_python",
        notes="Release and cutover gate behavior is Python-owned and covered by release gate and cutover truth tests.",
        current_behavior="Release and doctor readiness checks now use the Python runtime readiness contract and parity manifest as their source of truth.",
        missing_python_behavior="Keep the release gate aligned with runtime readiness and parity freshness, then cover the retained contract directly in Python tests.",
        python_owner_module="python/envctl_engine/runtime/release_gate.py",
        proposed_tests=(
            "tests/python/runtime/test_release_shipability_gate.py",
            "tests/python/runtime/test_cutover_gate_truth.py",
        ),
        severity="low",
        rollout_risk="This is mainly a developer-workflow risk, but confusing gates slow down confident cutover decisions.",
        wave="Wave E",
    ),
)
