from __future__ import annotations

from collections.abc import Callable, Mapping
from pathlib import Path
from typing import Protocol

from envctl_engine.config import EngineConfig
from envctl_engine.requirements.orchestrator import RequirementOutcome
from envctl_engine.runtime.command_router import Route
from envctl_engine.shared.hooks import HookInvocationResult
from envctl_engine.shared.protocols import PortAllocator, ProcessRuntime
from envctl_engine.state.models import PortPlan, RequirementsResult, RunState, ServiceRecord
from envctl_engine.ui.selection_types import TargetSelection


class ProjectContextLike(Protocol):
    name: str
    root: Path
    ports: Mapping[str, PortPlan]


class StartupRuntime(Protocol):
    config: EngineConfig
    env: Mapping[str, str]
    events: list[dict[str, object]]
    process_runner: ProcessRuntime
    port_planner: PortAllocator
    runtime_root: Path
    _conflict_remaining: dict[str, int]

    def _emit(self, event: str, **payload: object) -> None: ...
    def _reserve_project_ports(self, context: ProjectContextLike) -> None: ...
    def _requirements_ready(self, result: RequirementsResult) -> bool: ...
    def _assert_project_services_post_start_truth(
        self, *, context: ProjectContextLike, services: dict[str, ServiceRecord]
    ) -> None: ...
    def _terminate_started_services(self, services: dict[str, ServiceRecord]) -> None: ...
    def _try_load_existing_state(self, *, mode: str, strict_mode_match: bool = False) -> RunState | None: ...
    def _requirement_enabled(self, requirement_name: str, *, mode: str, route: Route | None = None) -> bool: ...
    def _service_enabled_for_mode(self, mode: str, service_name: str) -> bool: ...
    def _set_plan_port_from_component(self, plan: PortPlan, component: dict[str, object]) -> None: ...
    def _set_plan_port(self, plan: PortPlan, port: int) -> None: ...
    def _invoke_envctl_hook(self, *, context: ProjectContextLike, hook_name: str) -> HookInvocationResult: ...
    def _requirements_result_from_hook_payload(
        self, *, context: ProjectContextLike, mode: str, payload: dict[str, object]
    ) -> RequirementsResult: ...
    def _start_requirement_component(
        self,
        context: ProjectContextLike,
        name: str,
        plan: PortPlan,
        reserve_next: Callable[[int], int],
        *,
        strict: bool = False,
        route: Route | None = None,
    ) -> RequirementOutcome: ...
    def _skipped_requirement(self, service_name: str, plan: PortPlan) -> RequirementOutcome: ...
    def _command_exists(self, command: str) -> bool: ...
    def _project_name_from_service(self, service_name: str) -> str: ...
    def _select_project_targets(
        self,
        *,
        prompt: str,
        projects: list[ProjectContextLike],
        allow_all: bool,
        allow_untested: bool,
        multi: bool,
        initial_project_names: list[str] | None = None,
    ) -> TargetSelection: ...
    def _can_interactive_tty(self) -> bool: ...
    def _effective_start_mode(self, route: Route) -> str: ...
    def _startup_hook_contract_issue(self) -> str | None: ...
    def _validate_mode_toggles(self, mode: str, *, route: Route | None = None) -> None: ...
    def _release_requirement_ports(self, requirements: RequirementsResult) -> None: ...
    def _terminate_services_from_state(
        self,
        state: RunState,
        *,
        selected_services: set[str] | None = None,
        aggressive: bool = False,
        verify_ownership: bool = False,
    ) -> None: ...
    def _enforce_runtime_readiness_contract(self, *, scope: str) -> bool: ...
    def _new_run_id(self) -> str: ...
    def _current_session_id(self) -> str | None: ...
    def _discover_projects(self, *, mode: str) -> list[ProjectContextLike]: ...
    def _select_plan_projects(
        self, route: Route, project_contexts: list[ProjectContextLike]
    ) -> list[ProjectContextLike]: ...
    def _apply_setup_worktree_selection(
        self, route: Route, project_contexts: list[ProjectContextLike]
    ) -> list[ProjectContextLike]: ...
    def _duplicate_project_context_error(self, project_contexts: list[ProjectContextLike]) -> str | None: ...
    def _tree_parallel_startup_config(self, route: Route) -> tuple[bool, int]: ...
    def _load_auto_resume_state(self) -> object | None: ...
    def _auto_resume_start_enabled(self, route: Route) -> bool: ...
    def _resume(self, state: object, route: Route) -> int: ...
    def _reconcile_state_truth(self, state: RunState, *, emit_events: bool = True) -> RunState: ...
    def _start_project_context(
        self, *, context: ProjectContextLike, mode: str, route: Route, run_id: str
    ) -> tuple[RequirementsResult, dict[str, ServiceRecord], list[str]]: ...
    def _run_dir_path(self, run_id: str) -> Path: ...
    def _project_service_env(
        self,
        context: ProjectContextLike,
        *,
        requirements: RequirementsResult,
        route: Route | None,
        service_name: str | None = None,
    ) -> dict[str, str]: ...
    def _project_service_env_internal(
        self, context: ProjectContextLike, *, requirements: RequirementsResult, route: Route | None
    ) -> dict[str, str]: ...
    def _resolve_backend_env_file(
        self, *, context: ProjectContextLike, backend_cwd: Path
    ) -> tuple[Path | None, bool]: ...
    def _resolve_frontend_env_file(self, *, context: ProjectContextLike, frontend_cwd: Path) -> Path | None: ...
    def _services_from_hook_payload(
        self, *, context: ProjectContextLike, payload: dict[str, object]
    ) -> dict[str, ServiceRecord]: ...
    def _service_env_from_file(
        self,
        *,
        base_env: Mapping[str, str],
        env_file: Path | None,
        include_app_env_file: bool,
    ) -> dict[str, str]: ...
    def _prepare_backend_runtime(self, **kwargs: object) -> None: ...
    def _prepare_frontend_runtime(self, **kwargs: object) -> None: ...
    def _service_command_source(self, *, service_name: str, project_root: Path, port: int) -> str | None: ...
    def _service_start_command_resolved(
        self, *, service_name: str, project_root: Path, port: int
    ) -> tuple[list[str], str]: ...
    def _command_env(self, *, port: int, extra: Mapping[str, str] | None = None) -> dict[str, str]: ...
    def _runtime_env_overrides(self, route: Route | None) -> dict[str, str]: ...
    def _detect_service_actual_port(self, *, pid: int | None, requested_port: int, service_name: str) -> int | None: ...
    def _listener_truth_enforced(self) -> bool: ...
    def _service_listener_failure_detail(self, *, log_path: str | Path, pid: int | None) -> str | None: ...
    def _wait_for_service_listener(
        self, *, requested_port: int, actual_port: int, pid: int | None, service_name: str
    ) -> None: ...
    def _refresh_service_listener_pids(self, service: ServiceRecord) -> None: ...
    def _run_interactive_dashboard_loop(
        self, *, route: Route, run_id: str, project_contexts: list[ProjectContextLike]
    ) -> int: ...
    def _write_artifacts(
        self,
        *,
        run_id: str,
        mode: str,
        project_contexts: list[ProjectContextLike],
        requirements_by_project: dict[str, RequirementsResult],
        services: dict[str, ServiceRecord],
    ) -> RunState: ...
    def _print_summary(self, state: RunState) -> None: ...
    def _should_enter_post_start_interactive(self, route: Route, state: RunState | None = None) -> bool: ...
    def _run_pr_action(self, route: Route, targets: list[ProjectContextLike]) -> int: ...
    def _reset_project_startup_warnings(self) -> None: ...
    def _consume_project_startup_warnings(self, project_name: str) -> list[str]: ...


class StartupOrchestratorLike(Protocol):
    runtime: StartupRuntime

    def _report_progress(self, route: Route, message: str, *, project: str | None = None) -> None: ...
    def start_project_services(
        self,
        context: ProjectContextLike,
        *,
        requirements: RequirementsResult,
        run_id: str,
        route: Route | None = None,
    ) -> dict[str, ServiceRecord]: ...
    def start_requirements_for_project(
        self,
        context: ProjectContextLike,
        *,
        mode: str,
        route: Route | None = None,
    ) -> RequirementsResult: ...
    def _restart_include_requirements(self, route: Route) -> bool: ...
    def _restart_service_types_for_project(
        self,
        *,
        route: Route | None,
        project_name: str,
        default_service_types: set[str] | None = None,
    ) -> set[str]: ...
    def _suppress_timing_output(self, route: Route | None) -> bool: ...
    def _process_runtime(self, runtime: StartupRuntime) -> ProcessRuntime: ...
