from __future__ import annotations

import json
from pathlib import Path
import subprocess
import sys
from typing import Any, Callable

from envctl_engine.shared.parsing import parse_bool

DEFAULT_SHIP_PR_LABEL = "envctl"
DEFAULT_SHIP_PR_LABEL_COLOR = "5319e7"
DEFAULT_SHIP_PR_LABEL_DESCRIPTION = "Pull requests generated by envctl ship"
SHIP_PR_LABEL_ENABLE_ENV = "ENVCTL_SHIP_PR_LABEL_ENABLE"
SHIP_PR_LABEL_ENV = "ENVCTL_SHIP_PR_LABEL"


def ship_pr_label_enabled(context: Any) -> bool:
    env = getattr(context, "env", {})
    return parse_bool(env.get(SHIP_PR_LABEL_ENABLE_ENV), False)


def ship_pr_label(context: Any) -> str:
    env = getattr(context, "env", {})
    label = str(env.get(SHIP_PR_LABEL_ENV, DEFAULT_SHIP_PR_LABEL)).strip()
    return label


def add_ship_pr_label(
    context: Any,
    git_root: Path,
    pr_url: str,
    *,
    gh_path: str | None,
    run_process: Callable[..., subprocess.CompletedProcess[str]],
) -> int:
    if not ship_pr_label_enabled(context):
        return 0

    label = ship_pr_label(context)
    if not label:
        return 0
    if gh_path is None:
        _print_error("ship: gh is required to add the PR label")
        return 1

    ensure_code = _ensure_label(
        label,
        git_root=git_root,
        gh_path=gh_path,
        run_process=run_process,
    )
    if ensure_code != 0:
        return 1

    edited = run_process(
        [gh_path, "pr", "edit", pr_url, "--add-label", label],
        cwd=str(git_root),
        text=True,
        capture_output=True,
        check=False,
    )
    if edited.returncode != 0:
        _print_error("ship: failed to add PR label", edited)
        return 1
    return 0


def _ensure_label(
    label: str,
    *,
    git_root: Path,
    gh_path: str,
    run_process: Callable[..., subprocess.CompletedProcess[str]],
) -> int:
    listed = run_process(
        [gh_path, "label", "list", "--search", label, "--json", "name"],
        cwd=str(git_root),
        text=True,
        capture_output=True,
        check=False,
    )
    if listed.returncode != 0:
        _print_error("ship: failed to list PR labels", listed)
        return 1
    if _label_exists(label, listed.stdout):
        return 0

    created = run_process(
        [
            gh_path,
            "label",
            "create",
            label,
            "--color",
            DEFAULT_SHIP_PR_LABEL_COLOR,
            "--description",
            DEFAULT_SHIP_PR_LABEL_DESCRIPTION,
        ],
        cwd=str(git_root),
        text=True,
        capture_output=True,
        check=False,
    )
    if created.returncode != 0:
        _print_error("ship: failed to create PR label", created)
        return 1
    return 0


def _label_exists(label: str, label_json: str) -> bool:
    try:
        labels = json.loads(label_json or "[]")
    except json.JSONDecodeError:
        return False
    if not isinstance(labels, list):
        return False
    return any(isinstance(item, dict) and item.get("name") == label for item in labels)


def _print_error(prefix: str, result: subprocess.CompletedProcess[str] | None = None) -> None:
    if result is None:
        print(prefix, file=sys.stderr)
        return
    output = str(result.stderr or result.stdout or f"exit:{result.returncode}").strip()
    print(f"{prefix}: {output}", file=sys.stderr)


__all__ = [
    "DEFAULT_SHIP_PR_LABEL",
    "SHIP_PR_LABEL_ENABLE_ENV",
    "SHIP_PR_LABEL_ENV",
    "add_ship_pr_label",
    "ship_pr_label",
    "ship_pr_label_enabled",
]
