from __future__ import annotations

from .command_policy import (
    ACTION_COMMANDS,
    LIFECYCLE_CLEANUP_COMMANDS,
    STATE_ACTION_COMMANDS,
)


def _unique_tokens(*, registry_name: str, tokens: tuple[str, ...]) -> set[str]:
    seen: set[str] = set()
    duplicates: list[str] = []
    for token in tokens:
        if token in seen and token not in duplicates:
            duplicates.append(token)
            continue
        seen.add(token)
    if duplicates:
        joined = ", ".join(duplicates)
        raise RuntimeError(f"Duplicate tokens in {registry_name}: {joined}")
    return seen


def _unique_mapping(*, registry_name: str, pairs: tuple[tuple[str, str], ...]) -> dict[str, str]:
    mapping: dict[str, str] = {}
    duplicates: list[str] = []
    for key, value in pairs:
        if key in mapping:
            if key not in duplicates:
                duplicates.append(key)
            continue
        mapping[key] = value
    if duplicates:
        joined = ", ".join(duplicates)
        raise RuntimeError(f"Duplicate keys in {registry_name}: {joined}")
    return mapping


MODE_TREE_TOKENS = {
    "--tree",
    "--tree=true",
    "--trees",
    "--trees=true",
    "tree=true",
    "trees=true",
    "TREE=true",
    "TREES=true",
}
MODE_MAIN_TOKENS = {"--main", "--main=true", "main=true", "MAIN=true"}
MODE_FORCE_MAIN_TOKENS = {
    "--tree=false",
    "--trees=false",
    "tree=false",
    "trees=false",
    "TREE=false",
    "TREES=false",
}
MODE_FORCE_TREES_TOKENS = {"main=false", "MAIN=false"}
MODE_FALSE_TOKENS = MODE_FORCE_MAIN_TOKENS.union(MODE_FORCE_TREES_TOKENS)

DEFAULT_HEADLESS_COMMANDS = ACTION_COMMANDS | LIFECYCLE_CLEANUP_COMMANDS | STATE_ACTION_COMMANDS

_BOOLEAN_FLAG_TOKENS = (
    "--all",
    "--untested",
    "--failed",
    "--load-state",
    "--command-resume",
    "--skip-startup",
    "--command-only",
    "--logs-follow",
    "--logs-no-color",
    "--dashboard-interactive",
    "--interactive",
    "--headless",
    "--batch",
    "--json",
    "--stdin-json",
    "--non-interactive",
    "--no-interactive",
    "-b",
    "-f",
    "--dry-run",
    "--run",
    "--yes",
    "--force",
    "--deps-parallel",
    "--parallel-deps",
    "--requirements-parallel",
    "--parallel-trees",
    "--test-parallel",
    "--service-parallel",
    "--service-prep-parallel",
    "--ignore-service-deps",
    "--refresh-cache",
    "--fast",
    "--fast-startup",
    "--docker",
    "--stop-docker-on-exit",
    "--docker-temp",
    "--temp-docker",
    "--keep-plan",
    "--clear-port-state",
    "--clear-ports",
    "--clear-port-cache",
    "--debug-trace",
    "--debug-trace-no-xtrace",
    "--debug-trace-no-stdio",
    "--debug-trace-no-interactive",
    "--main-services-local",
    "--main-local",
    "--main-services-remote",
    "--main-remote",
    "--key-debug",
    "--debug-ui",
    "--debug-ui-deep",
    "--debug-ui-include-doctor",
    "--reuse-existing-worktree",
    "--setup-worktree-existing",
    "--recreate-existing-worktree",
    "--setup-worktree-recreate",
    "--seed-requirements-from-base",
    "--copy-db-storage",
    "--no-resume",
    "--no-auto-resume",
    "--cmux",
    "--tmux",
    "--omx",
    "--ultragoal",
    "--ralph",
    "--team",
    "--goal",
    "--codex-goal",
    "--no-goal",
    "--no-codex-goal",
    "--codex",
    "--opencode",
    "--ulw",
    "--no-ulw-loop",
    "--new-session",
    "--with-codex-skills",
    "--confirm",
    "--strict",
    "--update-password",
    "--update-metadata",
)
BOOLEAN_FLAGS = _unique_tokens(registry_name="BOOLEAN_FLAGS", tokens=_BOOLEAN_FLAG_TOKENS)

VALUE_FLAGS = {
    "--service",
    "--set",
    "--pr-base",
    "--review-base",
    "--commit-message",
    "--commit-message-file",
    "--analyze-mode",
    "--review-mode",
    "--logs-tail",
    "--logs-duration",
    "--parallel-trees-max",
    "--debug-trace-log",
    "--include-existing-worktrees",
    "--setup-include-worktrees",
    "--log-profile",
    "--log-level",
    "--backend-log-profile",
    "--backend-log-level",
    "--frontend-log-profile",
    "--frontend-log-level",
    "--frontend-test-runner",
    "--test-parallel-max",
    "--cli",
    "--preset",
    "--session-id",
    "--run-id",
    "--scope-id",
    "--output-dir",
    "--timeout",
    "--debug-capture",
    "--debug-auto-pack",
    "--mode",
    "--email",
    "--password",
    "--metadata-json",
    "--app-metadata-json",
    "--locale",
    "--seed",
}

PAIR_FLAGS = {"--setup-worktrees", "--setup-worktree"}

SPECIAL_FLAGS = {
    "--backend",
    "--frontend",
    "--both",
    "--fullstack",
    "--dependencies",
    "--deps",
    "--entire-system",
    "--blast-keep-worktree-volumes",
    "--blast-remove-worktree-volumes",
    "--blast-remove-main-volumes",
    "--blast-keep-main-volumes",
    "--stop-all-remove-volumes",
    "--remove-volumes",
    "--test-sequential",
    "--no-test-parallel",
    "--service-sequential",
    "--no-service-parallel",
    "--service-prep-sequential",
    "--no-service-prep-parallel",
    "--deps-sequential",
    "--sequential-deps",
    "--requirements-sequential",
    "--no-requirements-parallel",
    "--only-backend",
    "--only-frontend",
    "--no-dependencies",
    "--no-deps",
    "--no-infra",
    "--no-infrastructure",
    "--shared-dep",
    "--shared-deps",
    "--shared-dependency",
    "--shared-dependencies",
    "--managed-dep",
    "--managed-deps",
    "--managed-dependency",
    "--managed-dependencies",
    "--no-external-dep",
    "--no-external-deps",
    "--no-external-dependency",
    "--no-external-dependencies",
    "--isolated-dep",
    "--isolated-deps",
    "--isolated-dependency",
    "--isolated-dependencies",
    "--separate-dep",
    "--separate-deps",
    "--separate-dependency",
    "--separate-dependencies",
}

_ENV_ASSIGNMENT_KEYS = {
    "FRONTEND_TEST_RUNNER",
    "frontend-test-runner",
    "PARALLEL_TREES_MAX",
    "parallel-trees-max",
    "RUN_SH_OPT_PARALLEL_TREES_MAX",
    "fresh",
    "FRESH",
    "resume",
    "RESUME",
    "docker",
    "DOCKER",
    "docker-temp",
    "DOCKER_TEMP",
    "force",
    "FORCE",
    "copy-db-storage",
    "COPY_DB_STORAGE",
    "seed-requirements-from-base",
    "SEED_REQUIREMENTS_FROM_BASE",
    "parallel-trees",
    "PARALLEL_TREES",
    "RUN_SH_OPT_PARALLEL_TREES",
    "test-parallel",
    "TEST_PARALLEL",
    "ENVCTL_ACTION_TEST_PARALLEL",
    "service-prep-parallel",
    "SERVICE_PREP_PARALLEL",
    "ENVCTL_SERVICE_PREP_PARALLEL",
    "test-parallel-max",
    "TEST_PARALLEL_MAX",
    "ENVCTL_ACTION_TEST_PARALLEL_MAX",
    "service-parallel",
    "SERVICE_PARALLEL",
    "ENVCTL_SERVICE_ATTACH_PARALLEL",
    "backend",
    "BACKEND",
    "frontend",
    "FRONTEND",
}

_COMMAND_ALIAS_PAIRS = (
    ("start", "start"),
    ("--plan", "plan"),
    ("plan", "plan"),
    ("parallel-plan", "plan"),
    ("--parallel-plan", "plan"),
    ("sequential-plan", "plan"),
    ("--sequential-plan", "plan"),
    ("--plan-selection", "plan"),
    ("--planning-envs", "plan"),
    ("--planning-prs", "plan"),
    ("--plan-parallel", "plan"),
    ("--plan-sequential", "plan"),
    ("--resume", "resume"),
    ("resume", "resume"),
    ("--list-commands", "list-commands"),
    ("list-commands", "list-commands"),
    ("--list-targets", "list-targets"),
    ("list-targets", "list-targets"),
    ("--list-trees", "list-trees"),
    ("list-trees", "list-trees"),
    ("--show-config", "show-config"),
    ("show-config", "show-config"),
    ("--show-state", "show-state"),
    ("show-state", "show-state"),
    ("--endpoints", "endpoints"),
    ("endpoints", "endpoints"),
    ("--explain-startup", "explain-startup"),
    ("explain-startup", "explain-startup"),
    ("--preflight", "preflight"),
    ("preflight", "preflight"),
    ("--help", "help"),
    ("-h", "help"),
    ("help", "help"),
    ("--doctor", "doctor"),
    ("--debug-pack", "debug-pack"),
    ("--debug-ui-pack", "debug-pack"),
    ("debug-pack", "debug-pack"),
    ("--debug-report", "debug-report"),
    ("debug-report", "debug-report"),
    ("--debug-last", "debug-last"),
    ("debug-last", "debug-last"),
    ("dashboard", "dashboard"),
    ("--dashboard", "dashboard"),
    ("config", "config"),
    ("--config", "config"),
    ("--init", "config"),
    ("doctor", "doctor"),
    ("--restart", "restart"),
    ("restart", "restart"),
    ("--stop", "stop"),
    ("stop", "stop"),
    ("s", "stop"),
    ("--kill", "stop"),
    ("kill", "stop"),
    ("--stop-all", "stop-all"),
    ("stop-all", "stop-all"),
    ("stopall", "stop-all"),
    ("--kill-all", "stop-all"),
    ("kill-all", "stop-all"),
    ("killall", "stop-all"),
    ("--blast-all", "blast-all"),
    ("blast-all", "blast-all"),
    ("blastall", "blast-all"),
    ("--logs", "logs"),
    ("logs", "logs"),
    ("l", "logs"),
    ("--clear-logs", "clear-logs"),
    ("clear-logs", "clear-logs"),
    ("logs-clear", "clear-logs"),
    ("--test", "test"),
    ("--tests", "test"),
    ("--test-focused", "test-focused"),
    ("test", "test"),
    ("tests", "test"),
    ("test-focused", "test-focused"),
    ("t", "test"),
    ("--errors", "errors"),
    ("errors", "errors"),
    ("e", "errors"),
    ("--health", "health"),
    ("health", "health"),
    ("h", "health"),
    ("--delete-worktree", "delete-worktree"),
    ("--delete-worktrees", "delete-worktree"),
    ("--remove-worktrees", "delete-worktree"),
    ("delete-worktree", "delete-worktree"),
    ("delete-worktrees", "delete-worktree"),
    ("remove-worktrees", "delete-worktree"),
    ("--blast-worktree", "blast-worktree"),
    ("--blast-worktrees", "blast-worktree"),
    ("blast-worktree", "blast-worktree"),
    ("blast-worktrees", "blast-worktree"),
    ("blastworktree", "blast-worktree"),
    ("--self-destruct-worktree", "self-destruct-worktree"),
    ("self-destruct-worktree", "self-destruct-worktree"),
    ("--pr", "pr"),
    ("--prs", "pr"),
    ("pr", "pr"),
    ("prs", "pr"),
    ("p", "pr"),
    ("--commit", "commit"),
    ("commit", "commit"),
    ("c", "commit"),
    ("--ship", "ship"),
    ("ship", "ship"),
    ("--review", "review"),
    ("review", "review"),
    ("reviews", "review"),
    ("v", "review"),
    ("--analyze", "review"),
    ("analyze", "review"),
    ("a", "review"),
    ("--migrate", "migrate"),
    ("migrate", "migrate"),
    ("migration", "migrate"),
    ("migrations", "migrate"),
    ("m", "migrate"),
    ("migrate-hooks", "migrate-hooks"),
    ("--migrate-hooks", "migrate-hooks"),
    ("install-prompts", "install-prompts"),
    ("--install-prompts", "install-prompts"),
    ("codex-tmux", "codex-tmux"),
    ("--codex-tmux", "codex-tmux"),
    ("ensure-worktree", "ensure-worktree"),
    ("--ensure-worktree", "ensure-worktree"),
    ("supabase-user", "supabase-user"),
    ("supabase-users", "supabase-user"),
    ("auth-user", "supabase-user"),
    ("--supabase-user", "supabase-user"),
    ("--supabase-users", "supabase-user"),
    ("--auth-user", "supabase-user"),
    ("qa-user", "qa-user"),
    ("qa-users", "qa-user"),
    ("--qa-user", "qa-user"),
    ("--qa-users", "qa-user"),
    ("playwright", "playwright"),
    ("--playwright", "playwright"),
    ("session", "session"),
    ("--session", "session"),
    ("dash", "dashboard"),
    ("d", "doctor"),
    ("r", "restart"),
)
COMMAND_ALIASES = _unique_mapping(registry_name="COMMAND_ALIASES", pairs=_COMMAND_ALIAS_PAIRS)

SUPPORTED_COMMANDS = sorted(
    {
        "start",
        "plan",
        "resume",
        "restart",
        "stop",
        "stop-all",
        "blast-all",
        "dashboard",
        "config",
        "doctor",
        "debug-pack",
        "debug-report",
        "debug-last",
        "test",
        "test-focused",
        "logs",
        "clear-logs",
        "health",
        "errors",
        "delete-worktree",
        "blast-worktree",
        "self-destruct-worktree",
        "pr",
        "commit",
        "ship",
        "review",
        "migrate",
        "migrate-hooks",
        "ensure-worktree",
        "supabase-user",
        "qa-user",
        "playwright",
        "install-prompts",
        "codex-tmux",
        "list-commands",
        "list-targets",
        "list-trees",
        "session",
        "show-config",
        "show-state",
        "endpoints",
        "explain-startup",
        "preflight",
        "help",
    }
)


def list_supported_commands() -> list[str]:
    return list(SUPPORTED_COMMANDS)


def list_supported_flag_tokens() -> list[str]:
    command_flags = {token for token in COMMAND_ALIASES if token.startswith("--")}
    mode_flags = {token for token in MODE_TREE_TOKENS.union(MODE_MAIN_TOKENS) if token.startswith("--")}
    explicit = {
        "--project",
        "--projects",
        "--command",
        "--action",
        "--no-parallel-trees",
        "--no-seed-requirements-from-base",
        "--no-copy-db-storage",
    }
    supported = (
        command_flags.union(mode_flags)
        .union(BOOLEAN_FLAGS)
        .union(VALUE_FLAGS)
        .union(PAIR_FLAGS)
        .union(SPECIAL_FLAGS)
        .union(explicit)
    )
    return sorted(supported)

