from __future__ import annotations

from envctl_engine.runtime.command_catalog_registry import unique_mapping

_COMMAND_ALIAS_PAIRS = (
    ("start", "start"),
    ("--plan", "plan"),
    ("plan", "plan"),
    ("--import", "import"),
    ("import", "import"),
    ("parallel-plan", "plan"),
    ("--parallel-plan", "plan"),
    ("sequential-plan", "plan"),
    ("--sequential-plan", "plan"),
    ("--plan-selection", "plan"),
    ("--planning-envs", "plan"),
    ("--planning-prs", "plan"),
    ("--plan-parallel", "plan"),
    ("--plan-sequential", "plan"),
    ("--resume", "resume"),
    ("resume", "resume"),
    ("--list-commands", "list-commands"),
    ("list-commands", "list-commands"),
    ("--list-targets", "list-targets"),
    ("list-targets", "list-targets"),
    ("--list-trees", "list-trees"),
    ("list-trees", "list-trees"),
    ("--show-config", "show-config"),
    ("show-config", "show-config"),
    ("--show-state", "show-state"),
    ("show-state", "show-state"),
    ("--endpoints", "endpoints"),
    ("endpoints", "endpoints"),
    ("--explain-startup", "explain-startup"),
    ("explain-startup", "explain-startup"),
    ("--preflight", "preflight"),
    ("preflight", "preflight"),
    ("--help", "help"),
    ("-h", "help"),
    ("help", "help"),
    ("--doctor", "doctor"),
    ("--debug-pack", "debug-pack"),
    ("--debug-ui-pack", "debug-pack"),
    ("debug-pack", "debug-pack"),
    ("--debug-report", "debug-report"),
    ("debug-report", "debug-report"),
    ("--debug-last", "debug-last"),
    ("debug-last", "debug-last"),
    ("dashboard", "dashboard"),
    ("--dashboard", "dashboard"),
    ("config", "config"),
    ("--config", "config"),
    ("--init", "config"),
    ("doctor", "doctor"),
    ("--restart", "restart"),
    ("restart", "restart"),
    ("--stop", "stop"),
    ("stop", "stop"),
    ("s", "stop"),
    ("--kill", "stop"),
    ("kill", "stop"),
    ("--stop-all", "stop-all"),
    ("stop-all", "stop-all"),
    ("stopall", "stop-all"),
    ("--kill-all", "stop-all"),
    ("kill-all", "stop-all"),
    ("killall", "stop-all"),
    ("--blast-all", "blast-all"),
    ("blast-all", "blast-all"),
    ("blastall", "blast-all"),
    ("--logs", "logs"),
    ("logs", "logs"),
    ("l", "logs"),
    ("--clear-logs", "clear-logs"),
    ("clear-logs", "clear-logs"),
    ("logs-clear", "clear-logs"),
    ("--test", "test"),
    ("--tests", "test"),
    ("--test-focused", "test-focused"),
    ("test", "test"),
    ("tests", "test"),
    ("test-focused", "test-focused"),
    ("t", "test"),
    ("--errors", "errors"),
    ("errors", "errors"),
    ("e", "errors"),
    ("--health", "health"),
    ("health", "health"),
    ("h", "health"),
    ("--delete-worktree", "delete-worktree"),
    ("--delete-worktrees", "delete-worktree"),
    ("--remove-worktrees", "delete-worktree"),
    ("delete-worktree", "delete-worktree"),
    ("delete-worktrees", "delete-worktree"),
    ("remove-worktrees", "delete-worktree"),
    ("--blast-worktree", "blast-worktree"),
    ("--blast-worktrees", "blast-worktree"),
    ("blast-worktree", "blast-worktree"),
    ("blast-worktrees", "blast-worktree"),
    ("blastworktree", "blast-worktree"),
    ("--self-destruct-worktree", "self-destruct-worktree"),
    ("self-destruct-worktree", "self-destruct-worktree"),
    ("--pr", "pr"),
    ("--prs", "pr"),
    ("pr", "pr"),
    ("prs", "pr"),
    ("p", "pr"),
    ("--commit", "commit"),
    ("commit", "commit"),
    ("c", "commit"),
    ("--ship", "ship"),
    ("ship", "ship"),
    ("--review", "review"),
    ("review", "review"),
    ("reviews", "review"),
    ("v", "review"),
    ("--analyze", "review"),
    ("analyze", "review"),
    ("a", "review"),
    ("--migrate", "migrate"),
    ("migrate", "migrate"),
    ("migration", "migrate"),
    ("migrations", "migrate"),
    ("m", "migrate"),
    ("migrate-hooks", "migrate-hooks"),
    ("--migrate-hooks", "migrate-hooks"),
    ("install-prompts", "install-prompts"),
    ("--install-prompts", "install-prompts"),
    ("codex-tmux", "codex-tmux"),
    ("--codex-tmux", "codex-tmux"),
    ("ensure-worktree", "ensure-worktree"),
    ("--ensure-worktree", "ensure-worktree"),
    ("supabase-user", "supabase-user"),
    ("supabase-users", "supabase-user"),
    ("auth-user", "supabase-user"),
    ("--supabase-user", "supabase-user"),
    ("--supabase-users", "supabase-user"),
    ("--auth-user", "supabase-user"),
    ("qa-user", "qa-user"),
    ("qa-users", "qa-user"),
    ("--qa-user", "qa-user"),
    ("--qa-users", "qa-user"),
    ("playwright", "playwright"),
    ("--playwright", "playwright"),
    ("session", "session"),
    ("--session", "session"),
    ("dash", "dashboard"),
    ("d", "doctor"),
    ("r", "restart"),
)
COMMAND_ALIASES = unique_mapping(registry_name="COMMAND_ALIASES", pairs=_COMMAND_ALIAS_PAIRS)

SUPPORTED_COMMANDS = sorted(
    {
        "start",
        "plan",
        "import",
        "resume",
        "restart",
        "stop",
        "stop-all",
        "blast-all",
        "dashboard",
        "config",
        "doctor",
        "debug-pack",
        "debug-report",
        "debug-last",
        "test",
        "test-focused",
        "logs",
        "clear-logs",
        "health",
        "errors",
        "delete-worktree",
        "blast-worktree",
        "self-destruct-worktree",
        "pr",
        "commit",
        "ship",
        "review",
        "migrate",
        "migrate-hooks",
        "ensure-worktree",
        "supabase-user",
        "qa-user",
        "playwright",
        "install-prompts",
        "codex-tmux",
        "list-commands",
        "list-targets",
        "list-trees",
        "session",
        "show-config",
        "show-state",
        "endpoints",
        "explain-startup",
        "preflight",
        "help",
    }
)


def list_supported_commands() -> list[str]:
    return list(SUPPORTED_COMMANDS)
