from __future__ import annotations

from envctl_engine.runtime.command_alias_catalog import COMMAND_ALIASES
from envctl_engine.runtime.command_catalog_registry import unique_tokens

MODE_TREE_TOKENS = {
    "--tree",
    "--tree=true",
    "--trees",
    "--trees=true",
    "tree=true",
    "trees=true",
    "TREE=true",
    "TREES=true",
}
MODE_MAIN_TOKENS = {"--main", "--main=true", "main=true", "MAIN=true"}
MODE_FORCE_MAIN_TOKENS = {
    "--tree=false",
    "--trees=false",
    "tree=false",
    "trees=false",
    "TREE=false",
    "TREES=false",
}
MODE_FORCE_TREES_TOKENS = {"main=false", "MAIN=false"}
MODE_FALSE_TOKENS = MODE_FORCE_MAIN_TOKENS.union(MODE_FORCE_TREES_TOKENS)

_BOOLEAN_FLAG_TOKENS = (
    "--all",
    "--untested",
    "--failed",
    "--load-state",
    "--command-resume",
    "--skip-startup",
    "--command-only",
    "--logs-follow",
    "--logs-no-color",
    "--dashboard-interactive",
    "--interactive",
    "--headless",
    "--batch",
    "--json",
    "--stdin-json",
    "--non-interactive",
    "--no-interactive",
    "-b",
    "-f",
    "--dry-run",
    "--run",
    "--yes",
    "--force",
    "--deps-parallel",
    "--parallel-deps",
    "--requirements-parallel",
    "--parallel-trees",
    "--test-parallel",
    "--service-parallel",
    "--service-prep-parallel",
    "--ignore-service-deps",
    "--refresh-cache",
    "--fast",
    "--fast-startup",
    "--docker",
    "--stop-docker-on-exit",
    "--docker-temp",
    "--temp-docker",
    "--keep-plan",
    "--clear-port-state",
    "--clear-ports",
    "--clear-port-cache",
    "--debug-trace",
    "--debug-trace-no-xtrace",
    "--debug-trace-no-stdio",
    "--debug-trace-no-interactive",
    "--main-services-local",
    "--main-local",
    "--main-services-remote",
    "--main-remote",
    "--key-debug",
    "--debug-ui",
    "--debug-ui-deep",
    "--debug-ui-include-doctor",
    "--reuse-existing-worktree",
    "--setup-worktree-existing",
    "--recreate-existing-worktree",
    "--setup-worktree-recreate",
    "--seed-requirements-from-base",
    "--copy-db-storage",
    "--no-resume",
    "--no-auto-resume",
    "--cmux",
    "--tmux",
    "--omx",
    "--ultragoal",
    "--ralph",
    "--team",
    "--goal",
    "--codex-goal",
    "--no-goal",
    "--no-codex-goal",
    "--codex",
    "--opencode",
    "--ulw",
    "--no-ulw-loop",
    "--new-session",
    "--with-codex-skills",
    "--confirm",
    "--strict",
    "--update-password",
    "--update-metadata",
)
BOOLEAN_FLAGS = unique_tokens(registry_name="BOOLEAN_FLAGS", tokens=_BOOLEAN_FLAG_TOKENS)

VALUE_FLAGS = {
    "--service",
    "--set",
    "--pr-base",
    "--review-base",
    "-m",
    "--commit-message",
    "--commit-message-file",
    "--analyze-mode",
    "--review-mode",
    "--logs-tail",
    "--logs-duration",
    "--parallel-trees-max",
    "--debug-trace-log",
    "--include-existing-worktrees",
    "--setup-include-worktrees",
    "--log-profile",
    "--log-level",
    "--backend-log-profile",
    "--backend-log-level",
    "--frontend-log-profile",
    "--frontend-log-level",
    "--frontend-test-runner",
    "--test-parallel-max",
    "--cli",
    "--preset",
    "--session-id",
    "--run-id",
    "--scope-id",
    "--output-dir",
    "--timeout",
    "--debug-capture",
    "--debug-auto-pack",
    "--mode",
    "--email",
    "--password",
    "--metadata-json",
    "--app-metadata-json",
    "--locale",
    "--seed",
}

PAIR_FLAGS = {"--setup-worktrees", "--setup-worktree"}

SPECIAL_FLAGS = {
    "--backend",
    "--frontend",
    "--both",
    "--fullstack",
    "--dependencies",
    "--deps",
    "--entire-system",
    "--blast-keep-worktree-volumes",
    "--blast-remove-worktree-volumes",
    "--blast-remove-main-volumes",
    "--blast-keep-main-volumes",
    "--stop-all-remove-volumes",
    "--remove-volumes",
    "--test-sequential",
    "--no-test-parallel",
    "--service-sequential",
    "--no-service-parallel",
    "--service-prep-sequential",
    "--no-service-prep-parallel",
    "--deps-sequential",
    "--sequential-deps",
    "--requirements-sequential",
    "--no-requirements-parallel",
    "--only-backend",
    "--only-frontend",
    "--no-dependencies",
    "--no-deps",
    "--no-infra",
    "--no-infrastructure",
    "--shared-dep",
    "--shared-deps",
    "--shared-dependency",
    "--shared-dependencies",
    "--managed-dep",
    "--managed-deps",
    "--managed-dependency",
    "--managed-dependencies",
    "--no-external-dep",
    "--no-external-deps",
    "--no-external-dependency",
    "--no-external-dependencies",
    "--isolated-dep",
    "--isolated-deps",
    "--isolated-dependency",
    "--isolated-dependencies",
    "--separate-dep",
    "--separate-deps",
    "--separate-dependency",
    "--separate-dependencies",
}

_ENV_ASSIGNMENT_KEYS = {
    "FRONTEND_TEST_RUNNER",
    "frontend-test-runner",
    "PARALLEL_TREES_MAX",
    "parallel-trees-max",
    "RUN_SH_OPT_PARALLEL_TREES_MAX",
    "fresh",
    "FRESH",
    "resume",
    "RESUME",
    "docker",
    "DOCKER",
    "docker-temp",
    "DOCKER_TEMP",
    "force",
    "FORCE",
    "copy-db-storage",
    "COPY_DB_STORAGE",
    "seed-requirements-from-base",
    "SEED_REQUIREMENTS_FROM_BASE",
    "parallel-trees",
    "PARALLEL_TREES",
    "RUN_SH_OPT_PARALLEL_TREES",
    "test-parallel",
    "TEST_PARALLEL",
    "ENVCTL_ACTION_TEST_PARALLEL",
    "service-prep-parallel",
    "SERVICE_PREP_PARALLEL",
    "ENVCTL_SERVICE_PREP_PARALLEL",
    "test-parallel-max",
    "TEST_PARALLEL_MAX",
    "ENVCTL_ACTION_TEST_PARALLEL_MAX",
    "service-parallel",
    "SERVICE_PARALLEL",
    "ENVCTL_SERVICE_ATTACH_PARALLEL",
    "backend",
    "BACKEND",
    "frontend",
    "FRONTEND",
}

_PARSER_ONLY_FLAGS = {
    "--project",
    "--projects",
    "--command",
    "--action",
    "--no-parallel-trees",
    "--no-seed-requirements-from-base",
    "--no-copy-db-storage",
}


def list_supported_flag_tokens() -> list[str]:
    command_flags = {token for token in COMMAND_ALIASES if token.startswith("--")}
    mode_flags = {token for token in MODE_TREE_TOKENS.union(MODE_MAIN_TOKENS) if token.startswith("--")}
    supported = (
        command_flags.union(mode_flags)
        .union(BOOLEAN_FLAGS)
        .union(VALUE_FLAGS)
        .union(PAIR_FLAGS)
        .union(SPECIAL_FLAGS)
        .union(_PARSER_ONLY_FLAGS)
    )
    return sorted(supported)
