from __future__ import annotations

from envctl_engine.runtime.help_topic_rendering import CommandHelpTopic


INSPECTION_HELP_TOPICS: dict[str, CommandHelpTopic] = {
    "logs": CommandHelpTopic(
        command="logs",
        summary="print logs for saved envctl-managed services",
        usage=("envctl logs [--project <name>|--service <name>|--all] [--logs-follow]",),
        what_it_does=(
            "reads saved run artifacts and service log paths from runtime state",
            "prints selected service logs with optional following and color policy controls",
        ),
        flags=(
            "--project <name>        show logs for selected project/worktree",
            "--service <name>        show logs for a specific saved service",
            "--all                   show all available logs",
            "--logs-follow           follow logs where supported",
            "--logs-tail <n>         limit displayed log lines where supported",
            "--logs-no-color         disable log highlighting",
        ),
        examples=("envctl logs --all", "envctl logs --project feature-a-1 --logs-follow"),
        aliases=("l", "--logs"),
        related=("errors", "health", "show-state"),
    ),
    "clear-logs": CommandHelpTopic(
        command="clear-logs",
        summary="clear selected saved service log files",
        usage=("envctl clear-logs [--project <name>|--service <name>|--all]",),
        what_it_does=(
            "loads current runtime state and truncates/removes selected envctl-owned log artifacts",
            "keeps service state metadata intact while clearing noisy local logs",
        ),
        flags=("--project <name>", "--service <name>", "--all"),
        examples=("envctl clear-logs --project feature-a-1", "envctl clear-logs --all"),
        aliases=("logs-clear", "--clear-logs"),
        related=("logs", "errors"),
    ),
    "health": CommandHelpTopic(
        command="health",
        summary="summarize saved service health and status",
        usage=("envctl health [--project <name>|--service <name>|--all] [--json]",),
        what_it_does=(
            "loads saved state and prints running/healthy/stale/unreachable service status",
            "uses envctl's status glyph policy so failures are easy to scan in terminal output",
        ),
        flags=("--project <name>", "--service <name>", "--all", "--json"),
        examples=("envctl health --all", "envctl health --project feature-a-1", "envctl health --json"),
        aliases=("h", "--health"),
        related=("logs", "errors", "dashboard"),
    ),
    "errors": CommandHelpTopic(
        command="errors",
        summary="surface known service errors and warning/error log lines",
        usage=("envctl errors [--project <name>|--service <name>|--all]",),
        what_it_does=(
            "combines saved service failure metadata with log scanning for error/warning patterns",
            "helps triage startup/runtime problems without opening every raw log manually",
        ),
        flags=("--project <name>", "--service <name>", "--all", "--logs-tail <n>"),
        examples=("envctl errors --all", "envctl errors --project feature-a-1"),
        aliases=("e", "--errors"),
        related=("logs", "health", "debug-pack"),
    ),
    "list-commands": CommandHelpTopic(
        command="list-commands",
        summary="print the supported runtime command inventory",
        usage=("envctl list-commands", "envctl list-commands --json"),
        what_it_does=(
            "prints every command known to the Python runtime router",
            "is useful for scripts, shell completion, and checking installed/runtime parity",
        ),
        flags=("--json",),
        examples=("envctl list-commands", "envctl list-commands --json"),
        aliases=("--list-commands",),
        related=("help",),
    ),
    "list-targets": CommandHelpTopic(
        command="list-targets",
        summary="list targetable projects for the selected mode",
        usage=("envctl list-targets [--main|--trees] [--json]",),
        what_it_does=(
            "discovers project/worktree targets without starting services",
            "in JSON mode includes ports, roots, selection hints, and running-state metadata where available",
        ),
        flags=("--main | --trees", "--json"),
        examples=("envctl list-targets --json", "envctl list-targets --trees"),
        aliases=("--list-targets",),
        related=("list-trees", "show-state", "test"),
    ),
    "show-config": CommandHelpTopic(
        command="show-config",
        summary="print effective envctl configuration",
        usage=("envctl show-config [--json]",),
        what_it_does=(
            "shows the resolved configuration from defaults, environment, and repo-local .envctl",
            "helps debug service commands, ports, managed keys, profiles, and UI settings",
        ),
        flags=("--json",),
        examples=("envctl show-config --json", "envctl show-config"),
        aliases=("--show-config",),
        related=("config", "preflight", "explain-startup"),
    ),
    "show-state": CommandHelpTopic(
        command="show-state",
        summary="print saved envctl runtime state",
        usage=("envctl show-state [--main|--trees] [--json]",),
        what_it_does=(
            "loads the saved run state for the selected mode/scope",
            "shows run/session IDs, service records, ports, logs, and runtime map data where available",
        ),
        flags=("--main | --trees", "--json"),
        examples=("envctl show-state --json", "envctl show-state --trees --json"),
        aliases=("--show-state",),
        related=("dashboard", "health", "logs", "session"),
    ),
    "explain-startup": CommandHelpTopic(
        command="explain-startup",
        summary="explain what envctl would start and why",
        usage=("envctl explain-startup [--main|--trees] [runtime scope] [--json]",),
        what_it_does=(
            "evaluates startup mode, scopes, dependency enablement, configured commands, and reuse decisions",
            "helps diagnose why envctl will or will not start a service before running startup",
        ),
        flags=("--main | --trees", "--backend|--frontend|--fullstack|--dependencies|--entire-system", "--json"),
        examples=("envctl explain-startup --json", "envctl explain-startup --trees --backend --json"),
        aliases=("--explain-startup",),
        related=("preflight", "show-config", "start"),
    ),
    "preflight": CommandHelpTopic(
        command="preflight",
        summary="print startup readiness/preflight information",
        usage=("envctl preflight [--main|--trees] [--json]",),
        what_it_does=(
            "runs lightweight startup/readiness analysis without launching services",
            "emits the versioned envctl.preflight.v1 contract in JSON mode",
        ),
        flags=("--main | --trees", "--json"),
        examples=("envctl preflight --json", "envctl preflight --trees --json"),
        aliases=("--preflight",),
        related=("explain-startup", "doctor", "show-config"),
    ),
    "endpoints": CommandHelpTopic(
        command="endpoints",
        summary="print project-scoped runtime URLs and dependency ports",
        usage=("envctl endpoints --project <name> --json", "envctl endpoints --project <name>"),
        what_it_does=(
            "loads the active saved runtime state and fails closed when the requested project is not running",
            "reports frontend/backend local and public URLs plus dependency ports for the selected project",
            "includes dependency_mode, shared_dependencies, and emits project-resolution success/failure events",
        ),
        flags=(
            "--project <name>        required unless exactly one project is active",
            "--json                  canonical automation output",
        ),
        examples=("envctl endpoints --project feature-a-1 --json",),
        aliases=("--endpoints",),
        related=("health", "show-state", "playwright"),
    ),
    "qa-user": CommandHelpTopic(
        command="qa-user",
        summary="ensure deterministic local QA credentials against the active project Supabase Auth",
        usage=(
            "envctl qa-user ensure --project <name> --email <email> --password <password> --json",
            "envctl qa-user ensure --project <name> --email <email> --password <password> --seed crm,calendar",
        ),
        what_it_does=(
            "resolves the requested active project before touching Supabase Auth",
            "creates the Auth user if missing or reuses the existing user idempotently",
            "updates existing users only when --update-password or --update-metadata is supplied",
            "writes a redacted qa-user-ensure.json artifact under the active run directory",
            "runs optional seed hooks from the selected project root and reports redacted stdout/stderr snippets",
        ),
        flags=(
            "--project <name>        required project guard",
            "--email <email>        QA Auth email",
            "--password <password>  local QA password echoed only in the JSON credentials payload",
            "--locale <locale>      optional user metadata locale",
            "--metadata-json <json> set user_metadata for create or --update-metadata",
            "--app-metadata-json <json> set app_metadata for create or --update-metadata",
            "--update-password      mutate an existing user's password; otherwise existing users are reused unchanged",
            "--update-metadata      mutate an existing user's metadata; otherwise existing users are reused unchanged",
            "--seed <names>         comma-separated seed domains; repeatable",
            "--json                 stable machine-readable result including artifact_path and project_resolution",
        ),
        examples=(
            "envctl qa-user ensure --project feature-a-1 --email qa@example.test --password local-secret --json",
        ),
        aliases=("qa-users", "--qa-user", "--qa-users"),
        related=("supabase-user", "endpoints", "playwright"),
    ),
    "playwright": CommandHelpTopic(
        command="playwright",
        summary="run a browser-test command against an already running project frontend",
        usage=("envctl playwright --project <name> -- <command>",),
        what_it_does=(
            "fails closed if the requested project or frontend endpoint is not active",
            "exports QA_BASE_URL and BASE_URL from envctl endpoint truth before running the passthrough command",
            "writes playwright-endpoints.json and exports ENVCTL_ENDPOINTS_JSON/ENVCTL_ENDPOINTS_JSON_PATH",
            "writes playwright-runtime-metadata.json under the run test-results directory "
            "with the endpoint artifact path",
        ),
        flags=(
            "--project <name>        required project guard",
            "--json                  print wrapper result as JSON",
            "--                    separates envctl flags from the passthrough command",
        ),
        examples=("envctl playwright --project feature-a-1 -- npx playwright test",),
        notes=(
            "use `envctl playwright --help` for wrapper help; tokens after `--` are treated as the command to run",
            "pass a concrete executable after `--`; for Playwright projects this is usually `npx playwright test`",
            "use `envctl endpoints --project <name> --json` first when you need to inspect resolved URLs",
        ),
        aliases=("--playwright",),
        related=("endpoints", "qa-user", "test"),
    ),
}
